### PR TITLE
Very Basic Point count

### LINKED ISSUE #39: "very" Basic Counting Scores

### PR DESCRIPTION
**Pull request by Altair115**
Closes #39
:hankey: Need further improvement

- !!! Random cards temp disabled to test counting better
- !!! Comments Added  for explanation

### CODE REVIEW

**Comment by Altair115** [comment]
Headache deluxe achieved

**Comment by AnotherFoxGuy** [comment]
Ben je hier nog mee bezig?

**Comment by Altair115** [comment]
the counting is done i don't know how to flip the cards back thou but the logic for it is there

**Comment by AnotherFoxGuy** [comment]
Zou je dit ook nog kunnen rebasen op master?

**Comment by Altair115** [comment]
HOW?

**Pull request merged**
